### PR TITLE
Pass full payload to Attribution

### PR DESCRIPTION
**Pull request by mgz**
## Description of the change

Pass full payload to Attribution.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by utsabc** [comment]
@mgz can you please share some context for this change it will be helpful for us :)

**Comment by mgz** [comment]
@utsabc since both Rudderstack and Attribution are Segment-compatible, we decided it is more future proof to forward the whole payload to us than to extract particular keys from it.

For example, we initially missed `context` key and now we see that `messageId` key is missing too after transformation.

With this change we won't have any missing keys.

**Comment by utsabc** [comment]
> @utsabc since both Rudderstack and Attribution are Segment-compatible, we decided it is more future proof to forward the whole payload to us than to extract particular keys from it.
> 
> For example, we initially missed `context` key and now we see that `messageId` key is missing too after transformation.
> 
> With this change we won't have any missing keys.

Thanks @mgz for your detailed explanation appreciate it

**Review by utsabc — APPROVED** [review]

**Comment by mgz** [comment]
@utsabc I have already signed it in the past, but signed again just now.

**Comment by utsabc** [comment]
> @utsabc I have already signed it in the past, but signed again just now.

Apologies I might have missed it thanks again

**Comment by utsabc** [comment]
@saikumarrs can you please review the PR tpp

**Review by saikumarrs — APPROVED** [review]

**Pull request merged**
