### PR TITLE
fix: one_signal:  Encode external_id in endpoint

### PR DESCRIPTION
**Pull request by anantjain45823**
## What are the changes introduced in this PR?

We are not encoding the external_id (like @ / + symbols) in endpoint ( for rack and group calls ) resulting in the root cause of a bug where one_signal throws an error  “No users with external_id found”

## What is the related Linear task?
Resolves INT-1696

## Please explain the objectives of your changes below

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [x] My code follows the style guidelines of this project

- [ ] **No breaking changes are being introduced.**

- [x] All related docs linked with the PR?

- [x] All changes manually tested?

- [x] Any documentation changes needed with this change?

- [x] Is the PR limited to 10 file changes?

- [x] Is the PR limited to one linear task?

- [x] Are relevant unit and component test-cases added?

### Reviewer checklist

- [x] Is the type of change in the PR title appropriate as per the changes?

- [x] Verified that there are no credentials or confidential data exposed with the changes.

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved URL encoding for `externalUserId` in OneSignal API requests to ensure compatibility.
	- Updated test URLs to include encoded characters, enhancing test reliability for email addresses.

### CODE REVIEW

**Comment by anantjain45823** [comment]
@coderabbitai review

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3140/test-report.html

**Comment by anantjain45823** [comment]
@saikumarrs We might need to check for breaking change for this

**Review by koladilip — APPROVED** [review]

**Comment by saikumarrs** [comment]
> @saikumarrs We might need to check for breaking change for this

Why do you think this is a breaking change?

**Review by saikumarrs — APPROVED** [review]

**Pull request merged**
