### PR TITLE
fix: clevertap remove stringification of array object properties

### PR DESCRIPTION
**Pull request by yashasvibajpai**
## What are the changes introduced in this PR?

Remove paylaod properties stringification for subscription group properties in case of
- profileData in user profiles (identify)

## What is the related Linear task?

Resolves INT-1513

## Please explain the objectives of your changes below

We need to add support for sending nested objects as it is to Clevertap. On investigation, it is found that this is only supported for upload profiles API (identify calls from Rudderstack). For events API (track calls from Rudderstack), it still returns an invalid response error like below

> "response": "{\"status\":\"fail\",\"processed\":0,\"unprocessed\":[{\"status\":\"fail\",\"code\":512,\"error\":\"Event data is incorrect. 512 - Only Items can have a nested structure, incorrect nested structure for field : prop1.Skipped record number : 1\",

So for events, we will continue supporting stringifying the nested objects before sending to Clevertap.

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

<hr>

### Developer checklist

- [x] My code follows the style guidelines of this project

- [x] **No breaking changes are being introduced.**

- [ ] All related docs linked with the PR?

- [x] All changes manually tested?

- [x] Any documentation changes needed with this change?

- [x] Is the PR limited to 10 file changes?

- [x] Is the PR limited to one linear task?

- [x] Are relevant unit and component test-cases added?

### Reviewer checklist

- [x] Is the type of change in the PR title appropriate as per the changes?

- [x] Verified that there are no credentials or confidential data exposed with the changes.

### CODE REVIEW

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3048/test-report.html

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3048/test-report.html

**Review by shrouti1507 — DISMISSED** [review]

**Review by ItsSudip — DISMISSED** [review]

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3048/test-report.html

**Review by shrouti1507 — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3048/test-report.html

**Review by utsabc — APPROVED** [review]

**Pull request merged**
