### PR TITLE
feat(integrations/auth0): include Auth0 event type in Rudderstack message

### PR DESCRIPTION
**Pull request by zenpaul**
## What are the changes introduced in this PR?

Include the Auth0 event code in the Rudderstack message produced by the Auth0 integration, under a new field name `source_type`.

I also added a unit test to ensure that empty batches of Auth0 events are handled correctly.

My org has submitted the CLA recently so that we may contribute this change. It is pending review from Rudderstack.

## What is the related Linear task?

There is none, this is a feature request. I can create a Github issue if needed.

## Please explain the objectives of your changes below

N/A

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

No backwards compatible changes are included.

### Any new dependencies introduced with this change?

No.

### Any new generic utility introduced or modified. Please explain the changes.

No.

### Any technical or performance related pointers to consider with the change?

No.

@coderabbitai review

<hr>

### Developer checklist

- [x] My code follows the style guidelines of this project

- [x] **No breaking changes are being introduced.**

- [x] All related docs linked with the PR?

- [x] All changes manually tested?

- [ ] Any documentation changes needed with this change?

- [x] Is the PR limited to 10 file changes?

- [x] Is the PR limited to one linear task?

- [x] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

### CODE REVIEW

**Comment by Gauravudia** [comment]
@zenpaul Thank you for the contribution. will review the PR soon. Meanwhile, please sign [this CLA](https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement)

**Comment by Gauravudia** [comment]
> My org has submitted the CLA recently so that we may contribute this change. It is pending review from Rudderstack.

Which org is this change related to?

**Comment by Gauravudia** [comment]
> My org has submitted the CLA recently so that we may contribute this change. It is pending review from Rudderstack.

 @zenpaul  Which org is this change related to?

**Comment by zenpaul** [comment]
@Gauravudia ZenBusiness Inc.

**Review by Gauravudia — DISMISSED** [review]

**Review by shrouti1507 — APPROVED** [review]

**Review by utsabc — DISMISSED** [review]

**Review by Gauravudia — APPROVED** [review]

**Review by utsabc — APPROVED** [review]

**Comment by zenpaul** [comment]
Thanks for the reviews and merge, y'all! Any information you can give me as to when this change will be released?

**Comment by gitcommitshow** [comment]
Hi @zenpaul , usually any merged PR should be available in the product within 2 weeks. So this should be available now.

**Pull request merged**
