### PR TITLE
Update eventMapping.js for `Order Completed`

### PR DESCRIPTION
**Pull request by darkv1nce**
Map 'Order Completed' to 'PURCHASE'

## What are the changes introduced in this PR?

Mapping `Order Completed` to `PURCHASE`

## What is the related Linear task?

N/A

## Please explain the objectives of your changes below

Mapping `Order Completed` to `PURCHASE` in Branch will allow completed orders and their associated properties (e.g. revenue) to be processed by Branch. 

### Any changes to existing capabilities/behaviour, mention the reason & what are the changes ?

Currently `Order Completed` is mapped to `ADD_PAYMENT_INFO` which is both intuitively not correct and prevents Branch from recognizing completed orders. 

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### Any technical or performance related pointers to consider with the change?

N/A

@coderabbitai review

<hr>

### Developer checklist

- [x ] My code follows the style guidelines of this project

- [x ] **No breaking changes are being introduced.**

- [x ] All related docs linked with the PR?

- [x ] All changes manually tested?

- [x ] Any documentation changes needed with this change?

- [ x] Is the PR limited to 10 file changes?

- [ x] Is the PR limited to one linear task?

- [ x] Are relevant unit and component test-cases added?

### Reviewer checklist

- [x ] Is the type of change in the PR title appropriate as per the changes?

- [x ] Verified that there are no credentials or confidential data exposed with the changes.

### CODE REVIEW

**Comment by anantjain45823** [comment]
@darkv1nce Is there any branch documentation around this event ?

**Comment by darkv1nce** [comment]
@anantjain45823 this the Branch event ontology: https://help.branch.io/developers-hub/docs/branch-event-ontology

**Comment by Gauravudia** [comment]
Hey @darkv1nce , Thanks for bringing this up. Updating the mapping from ADD_PAYMENT_INFO to PURCHASE can be breaking change for existing users of this destination. Therefore, we cannot accept this change at the moment. We plan to revamp this destination in the future, but we cannot commit to any timeline for it, as it is not prioritized at the moment

**Comment by darkv1nce** [comment]
@Gauravudia thanks. Makes sense. 

Any idea though on how I could work around the code so that I can send Order Completed as PURCHASE?

**Comment by darkv1nce** [comment]
breaking change

**Comment by saikumarrs** [comment]
@darkv1nce, unfortunately, there is no workaround as it's an issue in the code.
However, we're considering handling the breaking change more gracefully with a destination UI toggle if needed.

We'll make sure to keep you posted with the updates.

Thanks for raising this.

**Comment by Gauravudia** [comment]
@darkv1nce UI mapper support to override the default event mapping is released.

**Pull request closed without merging**
