### PR TITLE
chore(core): fix lints

### PR DESCRIPTION
**Pull request by utsabc**
## Description of the change

PR  to fix lints, as lint warnings are getting suppressed this poses vulnerabilities. Also applied prettier formatting to all applicable files

TODO: Address deepsource

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by saikumarrs** [comment]
@utsabc, thanks for initiating this. However, the plan is to enforce common formatting rules across the repository using prettier.
Do you mind if we fix these issues after that?

**Review by ItsSudip — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Review by shrouti1507 — APPROVED** [review]

**Comment by utsabc** [comment]
> @utsabc, thanks for initiating this. However, the plan is to enforce common formatting rules across the repository using prettier. Do you mind if we fix these issues after that?
> 
> We can do taht using prettier config any config we decided?

Not something major atleast lint upgrade is important hence wanted to merge this

**Comment by utsabc** [comment]
> > @utsabc, thanks for initiating this. However, the plan is to enforce common formatting rules across the repository using prettier. Do you mind if we fix these issues after that?
> > We can do taht using prettier config any config we decided?
> 
> Not something major atleast lint upgrade is important hence wanted to merge this

I have raised a separate PR for this @saikumarrs can you please check
https://github.com/rudderlabs/rudder-transformer/pull/1365

**Comment by saikumarrs** [comment]
Closing the PR to address these issues later.

**Pull request closed without merging**
