### PR TITLE
Feature(integration): Facebook Custom Audience API Version Upgrade

### PR DESCRIPTION
**Pull request by mihir-4116**
## Description of the change

> fb apis version upgraded from v13 to v14

## Type of change
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by mihir-4116** [comment]
Ready to review label added

**Comment by yashasvibajpai** [comment]
Are we confident that this update to v14 wouldn't affect existing functionalities?

**Comment by utsabc** [comment]
@mihir-4116 can we update the test cases to ga4 format please

**Comment by utsabc** [comment]
> Are we confident that this update to v14 wouldn't affect existing functionalities?

Yes they have tested

**Comment by mihir-4116** [comment]
> @mihir-4116 can we update the test cases to ga4 format pleas

**Comment by anantjain45823** [comment]
> > @mihir-4116 can we update the test cases to ga4 format pleas

@utsabc Updated the Test Cases . Can you check for the same?

**Review by utsabc — APPROVED** [review]

**Review by shrouti1507 — APPROVED** [review]

**Pull request merged**
