### PR TITLE
Bug Fix: Vulnerable packages upgraded

### PR DESCRIPTION
**Pull request by sanpj2292**
## Description of the change

The vulnerabilities mentioned in the Open-source issue attached to this PR has been fixed
- The base image has been updated to `node:14.19.0-alpine3.15` to fix vulnerabilities due to the base image
- Several dependencies have been updated to a version which doesn't have breaking changes
  - urijs
  - prompts
  -  uglify
  - minimist
  - ansi-regex
- Removed `prometheus-gc-stats` as it was having many issues related to it's dependent package versions
- Removed `minimist` as a direct dependency as it is not being used

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [x]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [x] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [x] Changes have been reviewed by at least one other engineer
- [x] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by sanpj2292** [comment]
docker scan vulnerabilities have been fixed in this PR

**Review by saikumarrs — APPROVED** [review]
LGTM. However, address the following non-blocking issues:
- Update the PR description to describe the changes clearly.
- Link the related GitHub issue.

**Comment by sanpj2292** [comment]
```bash
$ docker scan rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities

Testing rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities...

Organization:      rudderlabs
Package manager:   apk
Project name:      docker-image|rudderlabs/develop-rudder-transformer
Docker image:      rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities
Platform:          linux/amd64
Base image:        node:14.19.0-alpine3.15
Licenses:          enabled

✔ Tested 39 dependencies for known issues, no vulnerable paths found.

Your base image is out of date
1) Pull the latest version of your base image by running 'docker pull node:14.19.0-alpine3.15'
2) Rebuild your local image

-------------------------------------------------------

Testing rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities...

Organization:      rudderlabs
Package manager:   npm
Target file:       /home/node/app/data/package.json
Project name:      rudder-transformer
Docker image:      rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities
Licenses:          enabled

✔ Tested 1 dependencies for known issues, no vulnerable paths found.

-------------------------------------------------------

Testing rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities...

Organization:      rudderlabs
Package manager:   npm
Target file:       /home/node/app/package.json
Project name:      rudder-transformer
Docker image:      rudderlabs/develop-rudder-transformer:fix.package-vulnerabilities
Licenses:          enabled

✔ Tested 662 dependencies for known issues, no vulnerable paths found.


Tested 3 projects, no vulnerable paths were found.
```

**Comment by saikumarrs** [comment]
@sanpj2292 I noticed that you'd removed some packages too. Is there any other reason other than them being unnecessary?

**Comment by sanpj2292** [comment]
> @sanpj2292 I noticed that you'd removed some packages too. Is there any other reason other than them being unnecessary?

@saikumarrs As I mentioned earlier in the description about `prometheus-gc-stats`, there were too many other dependencies which needed to be upgraded, I was unsure if the changes made to it would have a breaking effect on the service metrics. Hence as it is not very critical at the moment, removed it. Please let me know if you have concerns about this or anything else

**Comment by saikumarrs** [comment]
> > @sanpj2292 I noticed that you'd removed some packages too. Is there any other reason other than them being unnecessary?
> 
> @saikumarrs As I mentioned earlier in the description about `prometheus-gc-stats`, there were too many other dependencies which needed to be upgraded, I was unsure if the changes made to it would have a breaking effect on the service metrics. Hence as it is not very critical at the moment, removed it. Please let me know if you have concerns about this or anything else

Is it the same with `minimist` package? I see it is incorrectly tagged as an updated package in the description.

**Comment by sanpj2292** [comment]
> Is it the same with minimist package? I see it is incorrectly tagged as an updated package in the description.

Not exactly, it is `minimist` has been removed from `package.json` as it is not being used directly. But some packages had minimist dependency so had to upgrade them. Hence you see it as an updated package in the description. Let me know if you need more clarification

**Comment by saikumarrs** [comment]
> > Is it the same with minimist package? I see it is incorrectly tagged as an updated package in the description.
> 
> Not exactly, it is `minimist` has been removed from `package.json` as it is not being used directly. But some packages had minimist dependency so had to upgrade them. Hence you see it as an updated package in the description. Let me know if you need more clarification

Cool. Let's clarify that `minimist` package was also removed.

**Review by utsabc — APPROVED** [review]

**Pull request merged**
