### PR TITLE
Test Router with latest response transform changes

### PR DESCRIPTION
**Pull request by arajguha**
## Description of the change
- Merged response transform branch into test-router branch
- Added a test success status field in API response
- refined API response for node sys error cases
- moved common functions to routerUtils

> Description here

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by arajguha** [comment]
Note: This branch has the Profitwell integration which is not currently in master.

**Review by sanpj2292 — COMMENTED** [review]
Please remove unnecessary commented code in the PR

**Comment by arajguha** [comment]
@akashrpo  please confirm on the Profitwell code in this PR.

**Comment by akashrpo** [comment]
LGTM

> @akashrpo please confirm on the Profitwell code in this PR.

**Review by sanpj2292 — APPROVED** [review]
LGTM

**Review by akashrpo — APPROVED** [review]

**Pull request merged**
