### PR TITLE
feature(new integration): onboarding custify destination

### PR DESCRIPTION
**Pull request by tataencu**
## Description of the change

Custify is a Customer Success platform designed for B2B Saas platforms. The destination supports RudderStack cloud calls for Identify, Group and Track calls and sends them to the Custify API.

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Development

- [x] Lint rules pass locally
- [x] The code changed/added as part of this pull request has been covered with tests
- [x] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by utsabc** [comment]
@tataencu Huge thanks for taking the initiative of developing this integration. As next steps we would want to do an end to end test for this integration and add the UI config before moving this for general availability, for which we would need a test account from your end for Custify.
Can you please help us with that ?

**Comment by tataencu** [comment]
> @tataencu Huge thanks for taking the initiative of developing this integration. As next steps we would want to do an end to end test for this integration and add the UI config before moving this for general availability, for which we would need a test account from your end for Custify.
> Can you please help us with that ?

@utsabc Sure thing, we will set up an account for you to use in the testing phase. What email shall we use for the primary user of the account? Also, we will push a small enhancement to the integration on Monday and update the PR accordingly.

**Comment by tataencu** [comment]
@utsabc also, there is an open PR for the config generator as well, if that helps: https://github.com/rudderlabs/config-generator/pull/31

**Comment by utsabc** [comment]
> > @tataencu Huge thanks for taking the initiative of developing this integration. As next steps we would want to do an end to end test for this integration and add the UI config before moving this for general availability, for which we would need a test account from your end for Custify.
> > Can you please help us with that ?
> 
> @utsabc Sure thing, we will set up an account for you to use in the testing phase. What email shall we use for the primary user of the account? Also, we will push a small enhancement to the integration on Monday and update the PR accordingly.

Sure, Please add utsab@rudderstack.com as the primary user for the account

**Comment by tataencu** [comment]
> utsab@rudderstack.com

@utsabc the Custify account was just created. We will be pushing the update I have mentioned before to the repository in the next few hours as well

**Comment by utsabc** [comment]
> > [utsab@rudderstack.com](mailto:utsab@rudderstack.com)
> 
> @utsabc the Custify account was just created. We will be pushing the update I have mentioned before to the repository in the next few hours as well

Awesome great news thanks @tataencu

**Comment by utsabc** [comment]
Hi @tataencu We are working on testing the integration it should done by this week. Till then can you please sign our CLA doc here :)
https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement

**Comment by utsabc** [comment]
> Hi @tataencu We are working on testing the integration it should done by this week. Till then can you please sign our CLA doc here :) https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement

Hey @tataencu we are waiting for the CLA sign we have a common customer waiting for this

**Comment by tataencu** [comment]
> > Hi @tataencu We are working on testing the integration it should done by this week. Till then can you please sign our CLA doc here :) https://rudderlabs.wufoo.com/forms/rudderlabs-contributor-license-agreement
> 
> Hey @tataencu aplogies I believe you have already signed this nps

Hey @utsabc, yes, I have already signed it twice :)

**Review by utsabc — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Pull request merged**
