### PR TITLE
fix: tiktok remove lowercasing for custom events

### PR DESCRIPTION
**Pull request by anantjain45823**
## What are the changes introduced in this PR?

For custom events we are lowering their event name but we should retain the message event case as these are case sensitive  at tiktok side

## Please explain the objectives of your changes below

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Type of change

If the pull request is a **bug-fix**, **enhancement** or a **refactor**, please fill in the details on the changes made.

- Existing capabilities/behavior

- New capabilities/behavior

If the pull request is a **new feature**,

### Any technical or performance related pointers to consider with the change?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### If the PR has changes in more than 10 files, please mention why the changes were not split into multiple PRs.

N/A

### If multiple linear tasks are associated with the PR changes, please elaborate on the reason:

N/A

<hr>

### Developer checklist

- [ ] **No breaking changes are being introduced.**

- [ ] Are all related docs linked with the PR?

- [ ] Are all changes manually tested?

- [ ] Does this change require any documentation changes?

- [ ] Are relevant unit and component test-cases added?

### Reviewer checklist

- [ ] Is the type of change in the PR title appropriate as per the changes?

- [ ] Verified that there are no credentials or confidential data exposed with the changes.

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved event handling logic for more accurate tracking in the TikTok Ads integration.

- **Tests**
	- Expanded test suite with new cases for TikTok Ads to ensure robustness and reliability.

### CODE REVIEW

**Comment by anantjain45823** [comment]
@coderabbitai review

**Comment by koladilip** [comment]
What about device mode?

**Review by koladilip — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Comment by sanpj2292** [comment]
Don't understand where lower-casing of event is happening 🤔

**Comment by anantjain45823** [comment]
> Don't understand where lower-casing of event is happening 🤔

@sanpj2292 L133 transform.js

**Comment by anantjain45823** [comment]
Moved to #2930

**Pull request closed without merging**
