### PR TITLE
fix: remove regex validation for phone_number

### PR DESCRIPTION
**Pull request by ujjwal-ab**
## Description of the change

Remove regex validation for phone_number (as is not required)

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by sanpj2292** [comment]
Is this part of CFD ?

**Comment by ujjwal-ab** [comment]
> Is this part of CFD ?

Yes, actually, tiktok did some changes in their doc due to which it came up.

**Comment by sanpj2292** [comment]
Got it. Do we have a Notion card or may be an alert or a slack conversation, using which we can have some context around this issue and keep a track as well ?

**Comment by ujjwal-ab** [comment]
> 



> Got it. Do we have a Notion card or may be an alert or a slack conversation, using which we can have some context around this issue and keep a track as well ?

Yes, [this](https://github.com/rudderlabs/rudder-transformer/pull/1771#issuecomment-1381393818) is the card.

**Comment by sanpj2292** [comment]
> > Got it. Do we have a Notion card or may be an alert or a slack conversation, using which we can have some context around this issue and keep a track as well ?

> Yes, https://github.com/rudderlabs/rudder-transformer/pull/1771#issuecomment-1381393818 is the card.

This contains the same github comment, can you correct it ?

**Comment by ujjwal-ab** [comment]
> > > Got it. Do we have a Notion card or may be an alert or a slack conversation, using which we can have some context around this issue and keep a track as well ?
> 
> > Yes, [#1771 (comment)](https://github.com/rudderlabs/rudder-transformer/pull/1771#issuecomment-1381393818) is the card.
> 
> This contains the same github comment, can you correct it ?

Updated

**Review by ItsSudip — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Review by sandeepdsvs — APPROVED** [review]

**Pull request merged**
