### PR TITLE
fix: posthog swapped alias ids

### PR DESCRIPTION
**Pull request by mjeffrey18**
## What are the changes introduced in this PR?

This PR fixes an issue with how the alias call is mapped when sending events from Rudderstack to PostHog. It ensures the distinct_id and alias are correctly populated in the $create_alias event sent to PostHog.

Whenever I call this on the client

```
rudderstack_client.alias(
  previous_id: "old-id",
  user_id: "keep-id"
)
```

The resulting $create_alias event sent to PostHog has the distinct_id and alias swapped:

```json
{
  "properties": {
    "distinct_id":  "old-id",
    "alias":  "keep-id"
  }
}  
```

According to the [PostHog docs](https://posthog.com/docs/product-analytics/identify#alias-assigning-multiple-distinct-ids-to-the-same-user), the distinct_id should be the ID we want to keep as the primary user identifier, and alias should be the secondary ID we want to merge into the primary.

## Solution

Update the transformer logic for the PostHog destination to correctly map:

- user_id from the Rudderstack alias call to distinct_id
- previous_id from the Rudderstack alias call to alias

After this change, the $create_alias event sent to PostHog for the example above should look like:

```json
{
  "properties": {
    "distinct_id": "keep-id",
    "alias": "old-id"
  }
}
```

### Developer checklist

- [x] My code follows the style guidelines of this project

- [x] **No breaking changes are being introduced.**

- [x] All related docs linked with the PR?

- [x] All changes manually tested?

- [x] Any documentation changes needed with this change?

- [x] Is the PR limited to 10 file changes?

- [-] Is the PR limited to one linear task?

- [-] Are relevant unit and component test-cases added in **new readability format**?

### Reviewer checklist

- [x] Is the type of change in the PR title appropriate as per the changes?

- [x] Verified that there are no credentials or confidential data exposed with the changes.

### CODE REVIEW

**Comment by gitcommitshow** [comment]
Thank you for your contribution @mjeffrey18 
Please [sign the CLA](https://forms.gle/CfXNsw8MMoLS3Z4g8). This is required for first-time contributors before merging a PR.

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Review by shrouti1507 — APPROVED** [review]

**Comment by krishna2020** [comment]
> Thank you for your contribution @mjeffrey18 Please [sign the CLA](https://forms.gle/CfXNsw8MMoLS3Z4g8). This is required for first-time contributors before merging a PR.

@mjeffrey18 can you sign the above CLA form ?

**Comment by gitcommitshow** [comment]
Hi @mjeffrey18 , I see you didn't get a chance to [sign the CLA](https://contributor.rudderlabs.com/cla?org=rudderlabs&repo=rudder-transformer&prNumber=3507&username=mjeffrey18).
Let me know if you're facing any issues with this or have any question about it?

It shouldn't take more than a min, it is a quick online form that requires your confirmation. This is required before merging the code. This ensures your contributed code can be used according to the project's license.

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Comment by shrouti1507** [comment]
@mjeffrey18 can you please sign the CLA so that we can go ahead

**Comment by mjeffrey18** [comment]
Hey guys, sorry for the delay. I tried to sign the CLA, but kept receipting a timeout.
Screenshot 2024-09-22 at 11 43 41

**Comment by gitcommitshow** [comment]
Hi @mjeffrey18, sorry about that error. Don't worry about it. 
You have **signed the CLA successfully** at `2024-09-22T07:41:16.425Z`.

@shrouti1507 you may go ahead with the review.

**Review by koladilip — APPROVED** [review]

**Review by shrouti1507 — COMMENTED** [review]
@mjeffrey18 can you edit the test cases as well? In files test/integrations/destinations/posthog/processor/data.ts and test/integrations/destinations/posthog/router/data.ts file. To confirm if the test cases are passing you can run `npm run test:ts -- component  --destination=posthog`

**Comment by gitcommitshow** [comment]
@mjeffrey18 this PR's changes has been released to production now

**Pull request merged**
