### PR TITLE
chore: onboard plugin framework

### PR DESCRIPTION
**Pull request by utsabc**
## What are the changes introduced in this PR?

Ref Design Doc: https://www.notion.so/rudderstacks/Integration-Plugin-26ff1465dd9b44f1b3a80239651152a5

This PR introduces onboarding of plugin integration framework to transformer, we take the approach of onboarding a new service aligning to the predefined interface to dictate the service structure

Major Piece of event order orchestration for transformer <> server contract lie in pluginAdapter.ts which after passing the events to integration plugin and handles the consistent structuring for responding back to outer layer

The pluginAdapter uses integration-store to get integration-plugin to do either processor/router transformer

Further we updated type definitions referencing from integrations-lib which acts as a common library

### CODE REVIEW

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/3481/test-report.html

**Comment by koladilip** [comment]
@utsabc update it once, conflicts or there

**Review by koladilip — APPROVED** [review]

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Pull request closed without merging**
