### PR TITLE
chore: upgrade isolated-vm from 4.5.0 to 4.6.0

### PR DESCRIPTION
**Pull request by debanjan97**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade isolated-vm from 4.5.0 to 4.6.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **1 version** ahead of your current version.
- The recommended version was released **6 months ago**, on 2023-07-25.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>isolated-vm</b></summary>
    <ul>
      <li>
        <b>4.6.0</b> - <a href="https://snyk.io/redirect/github/laverdet/isolated-vm/releases/tag/v4.6.0">2023-07-25</a></br>No content.
      </li>
      <li>
        <b>4.5.0</b> - <a href="https://snyk.io/redirect/github/laverdet/isolated-vm/releases/tag/v4.5.0">2023-03-08</a></br><p>Bump npm version -&gt; 4.5.0</p>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/laverdet/isolated-vm/releases">isolated-vm GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>isolated-vm</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/8f228c98668f01a117fc6312de51648a9c90fcdb">8f228c9</a> Bump npm version -&gt; 4.6.0</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/7c0a9f04bc5a5a64b8fa7e3c8caa9663a2a22e4c">7c0a9f0</a> Disable cpu-profiler test on CI</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/d36adc23a5fb52a618e5147ee41c61f0f5560d6a">d36adc2</a> Add c++17 flag on msbuild</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/0d7e6b27e6c63a729cddcc386f421fcee88d6878">0d7e6b2</a> Remove snapshot tests</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/22b7d1f0b01305357c61b140cc86925c27816a3e">22b7d1f</a> Action tweaks</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/f0681544949592d0eb8b55660de7de212a1d699b">f068154</a> Add std::optional #include</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/b508587c76d4ac5558ba7389990feec99b22a404">b508587</a> Support prebuild (#366)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/a1936c6e97bd1b31702d6b28640910f29d3a5693">a1936c6</a> Update README.md (#259)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/c65377ddd6732e296c0827357f5cc00dcd6f1738">c65377d</a> Update support engines (#362)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/a312cc6193dcf84c6c9b785c0cb3661574bf033a">a312cc6</a> Support OpenBSD (#372)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/acf59e4f09dabfe73a3f04f1dcb8eb8691b2a4f4">acf59e4</a> Types: Fix error on import (#369)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/5d9b9fe2f4c01e8a9ffd259afc687b87062beaec">5d9b9fe</a> Add .npmignore file (#367)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/097f58665138c12ec4e061a0adbeabbc19a57316">097f586</a> CI: Use Github Actions (#363)</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/3949464cee8353143a663ef91344a504901929f9">3949464</a> Update inspector example</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/35cb55adaac36d468a025c506ba8213e19620c89">35cb55a</a> Maybe fix FreeBSD</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/086279eab6b9957c884b8083527f4902b067e010">086279e</a> Fix OOM underflow</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/34d2325071234ec2161e483bf45cd431ed05e777">34d2325</a> README and unit test changes</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/48731824d724b52a0ed249953c6f38a5e05e968e">4873182</a> Fix callback with no name</li>
      <li><a href="https://snyk.io/redirect/github/laverdet/isolated-vm/commit/ab17bf65fb8a0064c3d30d8437b01f5d313f67e3">ab17bf6</a> Update alpine requirements in README.md (#353)</li>
    </ul>

   <a href="https://snyk.io/redirect/github/laverdet/isolated-vm/compare/9a3defebf80f4396290c608d7d3eabb1f95da92f...8f228c98668f01a117fc6312de51648a9c90fcdb">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/datamanagement/project/39f686fe-9e69-4343-a9ce-129e22bff288?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/datamanagement/project/39f686fe-9e69-4343-a9ce-129e22bff288/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/datamanagement/project/39f686fe-9e69-4343-a9ce-129e22bff288/settings/integration?pkg&#x3D;isolated-vm&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by koladilip — APPROVED** [review]

**Review by ItsSudip — APPROVED** [review]

**Comment by koladilip** [comment]
@Jayachand can you suggest if this can be merged safely?

**Review by sivashanmukh — APPROVED** [review]
LGTM

**Review by sivashanmukh — COMMENTED** [review]
~@koladilip which flow runs the tests? If the user transformations tests run successfully, this change should be good.~

**Review by sivashanmukh — COMMENTED** [review]
@koladilip We would like to do a mirror test on hosted before deploying

**Comment by koladilip** [comment]
> @koladilip We would like to do a mirror test on hosted before deploying

sure @sivashanmukh let me know once it is done

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Comment by devops-github-rudderstack** [comment]
This PR is considered to be stale. It has been open for 20 days with no further activity thus it is going to be closed in 7 days. To avoid such a case please consider removing the stale label manually or add a comment to the PR.

**Pull request closed without merging**
