### PR TITLE
fix: hubspot max batch limit for contacts

### PR DESCRIPTION
**Pull request by anantjain45823**
## What are the changes introduced in this PR?
This PR corrects the max batch limit for payload sent to hubspot as 100
Resolves INT-782
## Please explain the objectives of your changes below
Our configuration in `config.js` file mentions the maxBatchSize of payload sent to hubspot as 10 but it is 100 as can be checked from Hubspot docs [here](https://developers.hubspot.com/docs/api/crm/contacts#endpoint?spec=GET-/crm/v3/objects/contacts).
Additionally we checked this with load testing with 50K and 200K Load and everything looks great and event the time taken decreased significantly

Put down any required details on the broader aspect of your changes. If there are any dependent changes, **mandatorily** mention them here

### Type of change

**bug-fix**

- Existing capabilities/behaviour
    Previously data was sent to hubspot in a limit of upto 10 events per batch  
- New capabilities/behaviour
   Now data is sent to hubspot in a limit of upto 100 events per batch  
If the pull request is a **new feature**,

### Any technical or performance related pointers to consider with the change?

N/A

### Any new dependencies introduced with this change?

N/A

### Any new generic utility introduced or modified. Please explain the changes.

N/A

### If the PR has changes in more than 10 files, please mention why the changes were not split into multiple PRs.

N/A

### If multiple linear tasks are associated with the PR changes, please elaborate on the reason:

N/A

<hr>

### Developer checklist

- [x] **No breaking changes are being introduced.**

- [x] Are all related docs linked with the PR?

- [x] Are all changes manually tested?

- [x] Does this change require any documentation changes?

- [x] Are relevant unit and component test-cases added?

### Reviewer checklist

- [x] Is the type of change in the PR title appropriate as per the changes?

- [x] Verified that there are no credentials or confidential data exposed with the changes.

### CODE REVIEW

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/2952/test-report.html

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/2952/test-report.html

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/2952/test-report.html

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/2952/test-report.html

**Comment by devops-github-rudderstack** [comment]
Test report for this run is available at: https://test-integrations-dev.s3.amazonaws.com/integrations-test-reports/rudder-transformer/2952/test-report.html

**Review by utsabc — APPROVED** [review]

**Pull request merged**
