### PR TITLE
feat(tests): add batch disabled test cases for Google Cloud Function destination

### PR DESCRIPTION
**Pull request by RohitKhatta**
## Description of the change

> Batch Disable test cases for GCF
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by ItsSudip** [comment]
Do we need this pr? If not required, please close this with proper comments.

**Review by utsabc — DISMISSED** [review]

**Review by saikumarrs — CHANGES_REQUESTED** [review]
The "description" field is missing in the test case data. Can we please add it to all the existing and the new test cases?
CC @utsabc

**Comment by sanpj2292** [comment]
> The "description" field is missing in the test case data. Can we please add it to all the existing and the new test cases? CC @utsabc

For existing test-cases, I'd probably make it as part of another PR & in the current, I'd add the description field to google_cloud_function's test-case.

**Comment by RohitKhatta** [comment]
> The "description" field is missing in the test case data. Can we please add it to all the existing and the new test cases? CC @utsabc

added description

**Comment by utsabc** [comment]
> > The "description" field is missing in the test case data. Can we please add it to all the existing and the new test cases? CC @utsabc
> 
> added description

@RohitKhatta we have add descriptions in test cases similar to processor test cases

**Pull request closed without merging**
